development:
  adapter: postgresql
  encoding: unicode
  database: taskmanager_development
  pool: 5
  username: taskmanager
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  database: taskmanager_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: taskmanager_production
  pool: 5
  username: taskmanager
  password: pass


